spring:

  datasource:

    url: jdbc:mysql://localhost:3306/test

    driver-class-name: com.mysql.cj.jdbc.Driver

    username: root
    hikari:
      password: 135246adgsfh!
  jpa:

    show-sql: true

    hibernate:
      ddl-auto: create

  output:
    ansi:
      enabled: always

logging:
  level:
    org.hibernate.type: trace

